=== colameo/jhipster-base/src/JDLOptions.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "option": "dto",
                "baseType": "STRING",
                "values": [
                    "mapstruct",
                    "no"
                ],
                "description": "",
                "parseType": "Literal"
            },
            {
                "option": "pagination",
                "baseType": "STRING",
                "parseType": "Literal",
                "values": [
                    "infinite-scroll",
                    "pagination",
                    "no"
                ],
                "description": ""
            },
            {
                "option": "readOnly",
                "baseType": "BOOLEAN",
                "parseType": "Boolean",
                "values": [
                    "false"
                ],
                "description": ""
            }
        ],
        "additionalProperties": true,
        "required": [
            "option",
            "baseType",
            "parseType",
            "values",
            "description"
        ],
        "properties": {
            "option": {
                "$id": "#/items/properties/option",
                "type": "string",
                "title": "The Option Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "dto"
                ]
            },
            "baseType": {
                "$id": "#/items/properties/baseType",
                "type": "string",
                "title": "The Basetype Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "STRING"
                ]
            },
            "parseType": {
                "$id": "#/items/properties/parseType",
                "type": "string",
                "title": "The Parsetype Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Literal"
                ]
            },
            "values": {
                "$id": "#/items/properties/values",
                "type": "array",
                "title": "The Values Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "examples": [
                    [
                        "mapstruct",
                        "no"
                    ]
                ],
                "items": {
                    "$id": "#/items/properties/values/items",
                    "type": "string",
                    "title": "The Items Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "mapstruct",
                        "no"
                    ]
                }
            },
            "description": {
                "$id": "#/items/properties/description",
                "type": "string",
                "title": "The Description Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    ""
                ]
            }
        }
    }
}

=== colameo/jhipster-base/src/JDLApplicationOptions.json
[
  {
    "option": "applicationType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "monolith",
      "microservice",
      "gateway",
      "uaa"
    ],
    "description": "One of the listed values"
  },
  {
    "option": "blueprints",
    "baseType": "STRING",
    "parseType": "ListOfAnyLiterals",
    "values": [
    	"vuejs", 
    	"generator-jhipster-dotnetcore"
    ],
    "description": "Any blueprint identifier e.g. [vuejs] or [vuejs, generator-jhipster-dotnetcore]. Please note that the prefix 'generator-jhipster-' is optional."
  },
  {
    "option": "entitySuffix",
    "baseType": "STRING",
    "parseType": "JavaIdentifierLiteral",
    "values": [
      "Entity"
    ],
    "description": "Suffix for entities. false for empty string"
  },
  {
    "option": "serviceDiscoveryType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "eureka",
      "consul",
      "no",
      "false"
    ],
    "description": "One of the listed values"
  },
  {
    "option": "devDatabaseType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "h2Disk",
      "h2Memory",
      "mysql",
      "mariadb",
      "mssql",
      "postgresql",
      "oracle",
      "no",
      "mongodb",
      "cassandra",
      "couchbase"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "testFrameworks",
    "baseType": "LIST",
    "parseType": "ListOfLiterals",
    "values": [
      "protractor",
      "cucumber",
      "gatling"
    ],
    "description": "Braces mandatory"
  },
  {
    "option": "clientThemeVariant",
    "baseType": "STRING",
    "parseType": "AnyLiteral",
    "values": [
      "primary"
    ],
    "description": "You can put whatever value you want, provided you know it will work (like dark, or light)"
  },
  {
    "option": "dtoSuffix",
    "baseType": "STRING",
    "parseType": "JavaIdentifierLiteral",
    "values": [
      "DTO"
    ],
    "description": "Suffix for DTOs. false for empty string"
  },
  {
    "option": "nativeLanguage",
    "baseType": "STRING",
    "parseType": "LangIsoCode",
    "values": [
      "en"
    ],
    "description": "One of the languages as ISO code supported by JHipster"
  },
  {
    "option": "jwtSecretKey",
    "baseType": "STRING",
    "parseType": "Namespace",
    "values": [],
    "description": ""
  },
  {
    "option": "serverPort",
    "baseType": "INTEGER",
    "parseType": "Number",
    "values": [
      "8080",
      "8081",
      "9999"
    ],
    "description": "Depends on the app type"
  },
  {
    "option": "skipClient",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "true or false"
  },
  {
    "option": "messageBroker",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "kafka",
      "false"
    ],
    "description": "One of the listed values"
  },
  {
    "option": "cacheProvider",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "ehcache",
      "hazelcast",
      "caffeine",
      "infinispan",
      "memcached",
      "redis",
      "no"
    ],
    "description": "One of the listed values, ehcache for monoliths and gateways, hazelcast otherwise"
  },
  {
    "option": "websocket",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "spring-websocket",
      "false"
    ],
    "description": ""
  },
  {
    "option": "buildTool",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "maven",
      "gradle"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "packageName",
    "baseType": "STRING",
    "parseType": "Namespace",
    "values": [],
    "description": "Sets the packageFolder option"
  },
  {
    "option": "prodDatabaseType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "mysql",
      "mariadb",
      "mssql",
      "postgresql",
      "oracle",
      "no",
      "mongodb",
      "cassandra",
      "couchbase"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "baseName",
    "baseType": "STRING",
    "parseType": "AnyLiteral",
    "values": [
      "jhipster"
    ],
    "description": ""
  },
  {
    "option": "skipUserManagement",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "true"
    ],
    "description": ""
  },
  {
    "option": "enableTranslation",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "true"
    ],
    "description": ""
  },
  {
    "option": "languages",
    "baseType": "LIST",
    "parseType": "ListOfLangIsoCodes",
    "values": [
      "en",
      "fr"
    ],
    "description": "Braces are mandatory"
  },
  {
    "option": "searchEngine",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "elasticsearch",
      "false"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "jhiPrefix",
    "baseType": "STRING",
    "parseType": "JavaIdentifierLiteral",
    "values": [
      "jhi"
    ],
    "description": ""
  },
  {
    "option": "clientPackageManager",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "npm",
      "yarn"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "databaseType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "sql",
      "mongodb",
      "cassandra",
      "couchbase",
      "no"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "uaaBaseName",
    "baseType": "STRING",
    "parseType": "String",
    "values": [
      "\"../uaa\""
    ],
    "description": "Mandatory for gateway and microservices if auth type is uaa, must be between double-quotes"
  },
  {
    "option": "reactive",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "true or false"
  },
  {
    "option": "enableSwaggerCodegen",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "true or false"
  },
  {
    "option": "skipServer",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "true or false"
  },
  {
    "option": "clientFramework",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "angularX",
      "react"
    ],
    "description": "One of the listed values or one of the prod database type"
  },
  {
    "option": "enableHibernateCache",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "true"
    ],
    "description": "true or false"
  },
  {
    "option": "useSass",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [],
    "description": "true or false"
  },
  {
    "option": "authenticationType",
    "baseType": "STRING",
    "parseType": "EnumLiteral",
    "values": [
      "jwt",
      "uaa",
      "session",
      "oauth2"
    ],
    "description": "uaa for UAA apps, jwt otherwise"
  },
  {
    "option": "clientTheme",
    "baseType": "STRING",
    "parseType": "AnyLiteral",
    "values": [
      "none"
    ],
    "description": "You can put whatever value you want, provided you know it will work (like yeti)"
  }
]
